### ISSUE TITLE
Rmd header - inputs  to yaml

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#11]
linked to https://github.com/insightsengineering/coredev-roadmap/issues/11
We decided to limit the number of dependencies and we are using the low-level `yaml` package. This decision brings that we have to build a few own yaml utils.
There are already some examples https://github.com/insightsengineering/teal.reporter/blob/main/R/yaml_utils.R.
The shiny inputs for Rmd document specifications (type, theme, fontsize) have to be properly transform to yaml header.

from a `list` with shiny input we want to get a `string` which represent the yaml header of Rmd file.
There are many combinations of arguments and the yaml is very sensitive to small changes.

this process is NOT exposed to END USER, even NOT exposed to developer END USER, it is only for us.

Example of Rmd file:

```
---
author: "NEST"
title: "Report"
date: "07/04/2019"
output:
  pdf_document:
    keep_tex: yes
---
```
